version: 0.2

env:
  variables:
    TERRAFORM_VERSION: 1.2.1
    TF_DIRECTORY: infrastructure/terraform

phases:
  install:
    commands:
      - echo Starting install phase...
      - apt-get install -y wget
      - wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip -o terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - sudo mv terraform /bin
      - rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  
  pre_build:
    commands:
      - echo No pre_build commands.

  build:
    commands:
      - cd ${TF_DIRECTORY}
      - chmod +x terraform_script.sh
      - ./terraform_script.sh $ENVIRONMENT $TF_ACTION $COMMIT
